<?php

/**
 * @file
 * Contains confessional.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function confessional_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the confessional module.
    case 'help.page.confessional':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Drupal Alexa proof of concept') . '</p>';
      return $output;

    default:
  }
}
